### PR TITLE
feat: update template keepachangelog

### PR DESCRIPTION
**Pull request by rainchen**
changes:
* capitalized commit subject
* show author name for each commit
* sort commits by date
* unique commit subject to keep notable

### CODE REVIEW

**Comment by pawamoy** [comment]
Merging, thanks again!

**Comment by rainchen** [comment]
@pawamoy could you bump the version? so that I can upgrade the package with pip to DRY my projects which using this package.

**Comment by pawamoy** [comment]
Hey, sorry for the delay, will do that now.

**Comment by pawamoy** [comment]
Well, it seems I was sucked into a rabbit hole and I never released it :disappointed: 

It's done now!

**Pull request merged**
