### PR TITLE
perf: Fix performance issue when assigning previous version

### PR DESCRIPTION
**Pull request by chme**
I still encounter severe performance problems on a commit graph that has a lot of merge commits (each feature is developed in a feature branch; a version can have more than 20 merge commits - sorry for not testing this as part of #76).

The problematic code path is now in `build._assign_previous_versions`. It has the same issue that was fixed with #76 for grouping commits into versions.
The commit graph is traversed through all possible branches. Branching/merge commits result in the same commit being checked multiple times. 

With large commit graphs, I think, it is best to optimize it, to only follow the commit graph once and gather all information necessary. This PR will find the previous version information during the grouping of the commits.

I will do some more tests tomorrow, but would appreciate, if you could take a look at the proposed solution.

### CODE REVIEW

**Review by pawamoy — COMMENTED** [review]
I'll trust you again on this one. What would be nice is that we add fuzzing to the test suite: a test that runs the code on a big temp repo, with hundreds of commits, dozens of branches, etc., all randomly generated.

**Comment by chme** [comment]
I added a "test" that generates profiling data with cProfile. It has no assertions, not sure if it should have any ... 
The git repo is just a bunch of merges of one commit into main, but it illustrates the current issue well (see below).

I did run the test on different versions of the code:

| No. merge commit | 2.4.1     |         | PR 78   |         | 2.4.0   |         |
| ---------------- | --------- | ------- | ------- | ------- | ------- | ------- |
|                  | f calls   | seconds | f calls | seconds | f calls | seconds |
| 15               | 394,968   | 0.361   | 1,764   | 0.009   | 1,544   | 0.007   |
| 17               | 1,574,774 | 4.413   | 1,922    | 0.008   |   1,674      |  0.008       |
| 18               | 3,147,717 | 17.444  | 2,001    | 0.008   |     1,739    |    0.008     |

Note: the 2.4.0 version was not the "real" 2.4.0, but I just reverted the changes to build.py. And 2.4.1 was in reality the current `main` branch.

Running the test with 20 merges was unbearable with current main (I did not wait until it finished and aborted it ...).

My tests on a "real" git repo were successful with this PR applied. git-changelog was fast and it felt as if the response was instant.

For reference, here the generated files:

[perf_stats_2.4.0_15.txt](https://github.com/pawamoy/git-changelog/files/14671840/perf_stats_2.4.0_15.txt)
[perf_stats_2.4.0_17.txt](https://github.com/pawamoy/git-changelog/files/14671841/perf_stats_2.4.0_17.txt)
[perf_stats_2.4.0_18.txt](https://github.com/pawamoy/git-changelog/files/14671842/perf_stats_2.4.0_18.txt)
[perf_stats_now_15.txt](https://github.com/pawamoy/git-changelog/files/14671843/perf_stats_now_15.txt)
[perf_stats_now_17.txt](https://github.com/pawamoy/git-changelog/files/14671844/perf_stats_now_17.txt)
[perf_stats_now_18.txt](https://github.com/pawamoy/git-changelog/files/14671845/perf_stats_now_18.txt)
[perf_stats_pr78_15.txt](https://github.com/pawamoy/git-changelog/files/14671846/perf_stats_pr78_15.txt)
[perf_stats_pr78_17.txt](https://github.com/pawamoy/git-changelog/files/14671847/perf_stats_pr78_17.txt)
[perf_stats_pr78_18.txt](https://github.com/pawamoy/git-changelog/files/14671848/perf_stats_pr78_18.txt)

**Comment by pawamoy** [comment]
Amazing, thanks a lot!

Since it's not really a test, I'd move this profiling code to a task, in duties.py. Let me do that tomorrow :slightly_smiling_face:

**Comment by pawamoy** [comment]
Actually it's using Pytest fixtures so it could be hard to move that outside of a test run. So instead I think we can simply add a timeout to the test to make sure that it runs *fast*. WDYT?

**Comment by pawamoy** [comment]
So I tried both, and I don't like either one of the approach:

- adding a timeout or an assert on a timedelta makes the test flaky, I'm sure I'll regret this later
- rewriting as a task feels a bit heavy, and with this fix there's no further need for profiling (yet)

For reference, here the task I wrote:

```python
@duty
def profile(ctx: Context, merge: int = 15) -> None:
    """Profile the parsing and grouping of commits.

    Parameters:
        merge: Number of times to merge a branch in the temporary repository.
    """
    try:
        from tests.helpers import GitRepo
    except ModuleNotFoundError:
        import sys

        sys.path.insert(0, str(Path(__file__).parent))
        from tests.helpers import GitRepo

    def merge_branches(repo: GitRepo, branch: str = "feat", times: int = 15) -> None:
        for _ in range(times):
            repo.branch(branch)
            repo.checkout(branch)
            repo.commit(f"feat: {branch}")
            repo.checkout("main")
            repo.merge(branch)
            repo.git("branch", "-d", branch)

    with TemporaryDirectory() as tmp_dir:
        repo = GitRepo(Path(tmp_dir) / "repo")
        ctx.run(merge_branches, args=(repo, "feat", merge), title="Creating temporary repository")

        with Profile() as profile:
            Changelog(repo.path, convention=AngularConvention)
        Stats(profile).strip_dirs().sort_stats(SortKey.TIME).print_stats()
```

I'd say that we keep it here for reference but don't merge it yet. If we need to profile things again in the future, we can reconsider.

**Review by pawamoy — APPROVED** [review]
Thanks a lot for your hard work! :rocket:

**Pull request merged**
